import subprocess
Import('env', 'arch', 'common', 'cereal', 'messaging')

#print("getting boost")
#print(subprocess.run(["bash", "/data/openpilot/third_party/boost"], encoding='utf8'))

src = [
  'main.cc',
]

copyenv = env.Clone()

copyenv["CPPPATH"] += ["/data/boost/boost_1_80_0"]
copyenv["CCFLAGS"] += ["-Wno-error", "-Wno-shadow"]

libs = [common, cereal, messaging, 'capnp', 'zmq', 'kj', 'ssl', 'crypto', 'pthread', 'rt']
#copyenv.Program('wss', src, LIBS=libs)
copyenv.Program('wssServer', ['wssServer.cc'], LIBS=libs)

